[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
optimizer_runs = 8_000

remappings = [
  '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/',
  '@chainlink/contracts/=node_modules/@chainlink/contracts/',
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
  '@chainlink/contracts/src/v0.8/vendor/openzeppelin-solidity/v4.8.3/contracts/=node_modules/@openzeppelin/contracts/',
]

fs_permissions = [{ access = "read-write", path = "./" }]

[profile.env]
# API Keys
ETHERSCAN_API_KEY = "${ETHERSCAN_API_KEY}"

[rpc_endpoints]
eth_mainnet = "${RPC_URL_ETHEREUM}"
eth_testnet = "${RPC_URL_SEPOLIA}"
anvil = "http://localhost:8545"

[etherscan]
eth_testnet = { key = "${ETHERSCAN_API_KEY}", url = "${ETHERSCAN_TESTNET_VERIFIER_URL}", chain=11155111 }
eth_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "${ETHERSCAN_MAINNET_VERIFIER_URL}", chain=1 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
